"""render.py — turn the architecture graph + specs into human-readable Markdown.

Reads context/arch/graph.json, context/architecture.yml, context/files.yml and writes:
  - context/arch/GRAPH.md         : Mermaid diagrams (layer overview + curated backbone)
  - context/arch/INEFFICIENCY.md  : cycles, high fan-in/out, cross-layer edges, orphans
  - context/FILEMAP.md            : the file catalog as one table per layer

All outputs are GENERATED (regenerated by the architecture-maintainer); humans edit the
YAML sources, not these files.  Deterministic: everything is sorted.

Usage:  python context/arch/render.py [--quiet]
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import os
import sys
from collections import Counter, defaultdict

_HERE = os.path.dirname(os.path.abspath(__file__))
_CTX = os.path.dirname(_HERE)
_ROOT = os.path.dirname(_CTX)

try:
    import yaml
except ImportError:                                        # pragma: no cover
    sys.exit('render needs pyyaml (pip install -r requirements-docs.txt)')

_extract = None


def _layer_of(relpath, layers):
    global _extract
    if _extract is None:
        spec = importlib.util.spec_from_file_location('arch_extract', os.path.join(_HERE, 'extract.py'))
        _extract = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(_extract)
    return _extract.layer_of(relpath, layers)


def _load():
    graph = json.load(open(os.path.join(_HERE, 'graph.json'), encoding='utf-8'))
    arch = yaml.safe_load(open(os.path.join(_CTX, 'architecture.yml'), encoding='utf-8')) or {}
    files = {}
    fp = os.path.join(_CTX, 'files.yml')
    if os.path.isfile(fp):
        files = (yaml.safe_load(open(fp, encoding='utf-8')) or {}).get('files', {})
    return graph, arch, files


def _mid(s: str) -> str:
    """A Mermaid-safe node id."""
    return 'n' + ''.join(c if c.isalnum() else '_' for c in s)


# --- GRAPH.md ----------------------------------------------------------------------------
def render_graph_md(graph, arch) -> str:
    layers = arch.get('layers', [])
    by_id = {n['id']: n for n in graph['nodes']}
    layer_names = [lyr['name'] for lyr in layers]

    # layer-level import overview
    pair_counts = Counter()
    for e in graph['edges']:
        if e['kind'] != 'imports':
            continue
        sl = _layer_of(by_id[e['src']]['file'], layers)
        dl = _layer_of(by_id[e['dst']]['file'], layers)
        if sl and dl and sl != dl:
            pair_counts[(sl, dl)] += 1

    out = ['<!-- GENERATED by context/arch/render.py — do not edit by hand. -->',
           '# Architecture — call/import graph', '',
           'Derived from `context/arch/graph.json` (built from source by `extract.py`).', '',
           '## Layer import overview', '',
           'Cross-layer module imports (edge label = number of import statements).', '',
           '```mermaid', 'graph LR']
    for name in layer_names:
        if any(name in pair for pair in pair_counts):
            out.append(f'  {_mid(name)}["{name}"]')
    for (sl, dl), c in sorted(pair_counts.items()):
        out.append(f'  {_mid(sl)} -->|{c}| {_mid(dl)}')
    out.append('```')

    # curated backbone (function-level call structure)
    out += ['', '## Backbone call structure', '',
            'The curated caller→callee edges from `context/architecture.yml` '
            '(solid = calls, dashed = ref, dotted = dispatch).', '',
            '```mermaid', 'graph LR']
    seen = set()
    for e in arch.get('backbone', []):
        for anchor in (e['src'], e['dst']):
            key = f"{anchor['name']}@{anchor['file']}"
            if key not in seen:
                seen.add(key)
                label = f"{anchor['name']}<br/><small>{os.path.basename(anchor['file'])}</small>"
                out.append(f'  {_mid(key)}["{label}"]')
    arrow = {'calls': '-->', 'ref': '-.->', 'dispatch': '-..->'}
    for e in arch.get('backbone', []):
        s = _mid(f"{e['src']['name']}@{e['src']['file']}")
        d = _mid(f"{e['dst']['name']}@{e['dst']['file']}")
        out.append(f"  {s} {arrow.get(e.get('via', 'calls'), '-->')} {d}")
    out.append('```')
    out.append('')
    return '\n'.join(out)


# --- INEFFICIENCY.md ---------------------------------------------------------------------
def render_inefficiency_md(graph, arch) -> str:
    by_id = {n['id']: n for n in graph['nodes']}
    layers = arch.get('layers', [])
    call_edges = [e for e in graph['edges'] if e['kind'] in ('calls', 'ref', 'dispatch')]
    import_edges = [e for e in graph['edges'] if e['kind'] == 'imports']

    fan_out = Counter(e['src'] for e in call_edges)
    fan_in = Counter(e['dst'] for e in call_edges)

    out = ['<!-- GENERATED by context/arch/render.py — do not edit by hand. -->',
           '# Architecture — inefficiency signals', '',
           'Heuristics over `graph.json` to surface design smells. Not all are bugs; they are '
           'places to look when reasoning about coupling and dead code.', '']

    # module import cycles (networkx if available)
    out += ['## Module import cycles', '']
    cycles = _import_cycles(import_edges, by_id)
    if cycles is None:
        out.append('_networkx not installed — cycle detection skipped._')
    elif not cycles:
        out.append('None. The module import graph is acyclic. ✅')
    else:
        for cyc in cycles:
            out.append('- ' + ' → '.join(cyc))
    out.append('')

    # high fan-in / fan-out
    out += ['## Highest fan-out functions (call many callees)', '']
    out += _degree_table(fan_out, by_id)
    out += ['', '## Highest fan-in functions (called by many)', '']
    out += _degree_table(fan_in, by_id)

    # cross-layer call coupling
    out += ['', '## Cross-layer call coupling', '',
            'Call/ref/dispatch edges whose endpoints live in different layers.', '']
    xlayer = Counter()
    for e in call_edges:
        sl = _layer_of(by_id[e['src']]['file'], layers)
        dl = _layer_of(by_id[e['dst']]['file'], layers)
        if sl and dl and sl != dl:
            xlayer[(sl, dl)] += 1
    if xlayer:
        out.append('| From | To | Edges |')
        out.append('|---|---|---:|')
        for (sl, dl), c in sorted(xlayer.items(), key=lambda kv: (-kv[1], kv[0])):
            out.append(f'| {sl} | {dl} | {c} |')
    else:
        out.append('None.')

    # orphan public functions (public, zero incoming call/ref edges — dead code or entry points)
    out += ['', '## Orphan public functions', '',
            'Public functions with no incoming call/ref/dispatch edge — either entry points '
            'or dead code worth reviewing.', '']
    referenced = set(fan_in)
    orphans = sorted(n['id'] for n in graph['nodes']
                     if n['kind'] == 'function' and n.get('public')
                     and n['id'] not in referenced
                     and n['name'] not in ('main',))
    out.append(f'{len(orphans)} found (showing up to 40):')
    out.append('')
    for oid in orphans[:40]:
        n = by_id[oid]
        out.append(f"- `{n['name']}` — {n['file']}")
    out.append('')
    return '\n'.join(out)


def _import_cycles(import_edges, by_id):
    try:
        import networkx as nx
    except ImportError:
        return None
    g = nx.DiGraph()
    for e in import_edges:
        g.add_edge(by_id[e['src']]['file'], by_id[e['dst']]['file'])
    cycles = [c + [c[0]] for c in nx.simple_cycles(g)]
    return sorted(cycles, key=lambda c: (len(c), c))[:20]


def _degree_table(counter, by_id, top=15):
    rows = ['| Function | File | Degree |', '|---|---|---:|']
    for nid, deg in sorted(counter.items(), key=lambda kv: (-kv[1], kv[0]))[:top]:
        n = by_id[nid]
        rows.append(f"| `{n['name']}` | {n['file']} | {deg} |")
    return rows


# --- FILEMAP.md --------------------------------------------------------------------------
def render_filemap_md(arch, files) -> str:
    layer_order = [lyr['name'] for lyr in arch.get('layers', [])]
    by_layer = defaultdict(list)
    for relpath, e in files.items():
        by_layer[e.get('layer', 'unclassified')].append((relpath, e))

    out = ['<!-- GENERATED by context/arch/render.py from context/files.yml — do not edit by hand. -->',
           '# File map', '',
           'Every source + test file, its purpose, and key symbols. Grouped by architecture '
           'layer. Edit `purpose`/`notes` in `context/files.yml`, not here.', '',
           f'{len(files)} files catalogued.', '']
    for layer in layer_order + sorted(set(by_layer) - set(layer_order)):
        rows = sorted(by_layer.get(layer, []))
        if not rows:
            continue
        out += [f'## {layer}', '', '| File | Purpose | Key symbols |', '|---|---|---|']
        for relpath, e in rows:
            syms = ', '.join(f"`{s['name']}`" for s in (e.get('key_symbols') or [])[:6])
            purpose = str(e.get('purpose', '')).replace('|', '\\|')
            out.append(f'| `{relpath}` | {purpose} | {syms} |')
        out.append('')
    return '\n'.join(out)


def render_all(quiet: bool = False) -> list[str]:
    graph, arch, files = _load()
    written = []
    targets = [
        (os.path.join(_HERE, 'GRAPH.md'), render_graph_md(graph, arch)),
        (os.path.join(_HERE, 'INEFFICIENCY.md'), render_inefficiency_md(graph, arch)),
    ]
    if files:
        targets.append((os.path.join(_CTX, 'FILEMAP.md'), render_filemap_md(arch, files)))
    for path, text in targets:
        with open(path, 'w', encoding='utf-8', newline='\n') as fh:
            fh.write(text if text.endswith('\n') else text + '\n')
        written.append(os.path.relpath(path, _ROOT).replace(os.sep, '/'))
        if not quiet:
            print(f'wrote {written[-1]}')
    return written


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--quiet', action='store_true')
    args = ap.parse_args()
    render_all(quiet=args.quiet)
    return 0


if __name__ == '__main__':
    sys.exit(main())
